/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
//#include "SDWindowListview.h"
#include "SDWindow.h"
#include "ControlWindow.h"
#include "IconViewManager.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0              (GUI_ID_USER + 0x00)
#define ID_ICONVIEW_0            (GUI_ID_USER + 0x02)
#define ID_ICONVIEW_1            (GUI_ID_USER + 0x03)
#define ID_ICONVIEW_2            (GUI_ID_USER + 0x05)

#define ID_ICONVIEW_0_IMAGE_0   0x00			//Storage
#define ID_ICONVIEW_1_IMAGE_0   0x01			//Configuration
#define ID_ICONVIEW_2_IMAGE_0   0x02			//Setting

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "C:\Data\SCARA 3D Printer\res\sdicon.dta", ID_ICONVIEW_0_IMAGE_0
*/


// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
//  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_0, 26, 60, 128, 140, 0, 0x008c0080, 0 },
//  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_1, 179, 60, 128, 140, 0, 0x008c0080, 0 },
//  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_2, 327, 60, 128, 140, 0, 0x008c0080, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_ICONVIEW_0_IMAGE_0:
    *pSize = sizeof(Icon_0_Img);
    return (const void *)Icon_0_Img;
  case ID_ICONVIEW_1_IMAGE_0:
    *pSize = sizeof(Icon_1_Img);
    return (const void *)Icon_1_Img;
  case ID_ICONVIEW_2_IMAGE_0:
    *pSize = sizeof(Icon_2_Img);
    return (const void *)Icon_2_Img;
  }
  return NULL;
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
		ICONVIEW_EnableStreamAuto();
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00FF8080);
    //
    // Initialization of 'Iconview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_0);
    pData = _GetImageById(ID_ICONVIEW_0_IMAGE_0, &FileSize);
    
		WM_SetTransState(hItem, WM_CF_HASTRANS);
		hItem     = ICONVIEW_CreateEx(30, 60, 136, 170, pMsg -> hWin, WM_CF_SHOW | WM_CF_HASTRANS, 0, ID_ICONVIEW_0, 114, 160);
		ICONVIEW_SetFont(hItem,  &GUI_Font24B_1);
		ICONVIEW_AddStreamedBitmapItem(hItem, pData, " SD CARD");
		ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_TOP | ICONVIEW_IA_HCENTER);
		ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_SEL, (0x880000FF));
	  ICONVIEW_SetSpace(hItem, GUI_COORD_X, 15);
    //
    // Initialization of 'Iconview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_1);
    pData = _GetImageById(ID_ICONVIEW_1_IMAGE_0, &FileSize);
    
		WM_SetTransState(hItem, WM_CF_HASTRANS);
		hItem     = ICONVIEW_CreateEx(180, 60, 136, 170, pMsg -> hWin, WM_CF_SHOW | WM_CF_HASTRANS, 0, ID_ICONVIEW_1, 128, 160);
		ICONVIEW_SetFont(hItem,  &GUI_Font24B_1);
		ICONVIEW_AddStreamedBitmapItem(hItem, pData, "Control");
		ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_TOP | ICONVIEW_IA_HCENTER);
		ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_SEL, (0x880000FF));
    ICONVIEW_SetSpace(hItem, GUI_COORD_X, 17);
    //
    // Initialization of 'Iconview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_2);
    pData = _GetImageById(ID_ICONVIEW_2_IMAGE_0, &FileSize);
		WM_SetTransState(hItem, WM_CF_HASTRANS);

		hItem = ICONVIEW_CreateEx(330, 60, 136, 170, pMsg -> hWin, WM_CF_SHOW | WM_CF_HASTRANS, 0, ID_ICONVIEW_2, 114, 160);
    ICONVIEW_SetFont(hItem,  &GUI_Font24B_1);
		ICONVIEW_AddStreamedBitmapItem(hItem, pData, "Settings");
		ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_TOP | ICONVIEW_IA_HCENTER);
		ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_SEL, (0x880000FF));
    ICONVIEW_SetSpace(hItem, GUI_COORD_X, 17);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_0: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
						CreateSDWindow();
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_1: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
					CreateControlWindow();
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_2: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateMainWindow(void);
WM_HWIN CreateMainWindow(void) {
  WM_HWIN hWin;
//	while (1)
	{
	   GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
//		GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
//	   GUI_Delay(1000);
	}
//	while(1)
	{
//		GUI_Exec();
	}
//  WM_EnableWindow(hWin);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
